/**
 * Word data pipeline for 21kelime.
 *
 * Outputs:
 *   - src/lib/puzzles/data/words.json  { version, sources, validation, pools }
 *   - static/data-version.json         { version }
 *
 * POOLS ARE APPEND-ONLY, AND THAT IS LOAD-BEARING.
 *
 * Day N is generated by slicing pools[len] at a fixed offset, so the array
 * contents *are* the published puzzle schedule. Reordering or removing an
 * entry rewrites puzzles people have already played, and desyncs installed
 * apps: they compute puzzles on device from their own embedded copy, and
 * an offline one cannot be told the words moved. Appending is safe because
 * every index below the old length still resolves to the same word, so old
 * and new data agree on every day until the old pool would have wrapped.
 *
 * The rules, therefore:
 *   1. Never remove or reorder an entry already in words.json. Append only.
 *   2. Bump DATA_VERSION on every change, so online apps defer to the site.
 *   3. Every appended target must have a TDK entry (scripts/verify-tdk.ts);
 *      the result screen links each answer to sozluk.gov.tr.
 *
 * Run: node scripts/build-words.ts [--report] [--bootstrap]
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { hashSeed, mulberry32, shuffleInPlace } from '../src/lib/game/rng.ts';
import { loadSources, ROOT, TARGET_MIN, TARGET_MAX, FREQ_THRESHOLD } from './word-sources.ts';

const OUT_DIR = join(ROOT, 'src', 'lib', 'puzzles', 'data');
const OUT_PATH = join(OUT_DIR, 'words.json');
const TDK_CACHE = join(ROOT, 'data', 'tdk-verified.json');

/** Orders the words first published as data version 1. Never reused. */
const POOL_SHUFFLE_SEED = '21kelime-pools-v1';
/** Orders words appended in data version 2. Give later batches a new seed. */
const POOL_APPEND_SEED = '21kelime-pools-v2';

/**
 * Bump on ANY word data change. Installed apps compare this against the
 * site's /data-version.json and defer to the server when they differ.
 */
const DATA_VERSION = 2;

const SOURCES =
	'zemberek-nlp (Apache-2.0) master+non-tdk; hermitdave/FrequencyWords (MIT); TDK GTS (doğrulama)';

const report = process.argv.includes('--report');
const bootstrap = process.argv.includes('--bootstrap');

// ---- existing schedule ----

interface WordsFile {
	version: number;
	sources: string;
	validation: string[];
	pools: Record<string, string[]>;
}

const published: Record<number, string[]> = {};
if (existsSync(OUT_PATH)) {
	const prev = JSON.parse(readFileSync(OUT_PATH, 'utf8')) as WordsFile;
	for (const [len, list] of Object.entries(prev.pools)) published[Number(len)] = list;
} else if (!bootstrap) {
	throw new Error(
		`${OUT_PATH} yok. Yayındaki sıra bilinmeden havuz üretmek bütün geçmiş ve gelecek ` +
			`günleri değiştirir. Sıfırdan kurmak istiyorsan: node scripts/build-words.ts --bootstrap`
	);
}

// ---- TDK verification cache ----

const tdk: Record<string, 0 | 1> = existsSync(TDK_CACHE)
	? JSON.parse(readFileSync(TDK_CACHE, 'utf8'))
	: {};

// ---- build ----

const { validation, eligible, master, nonTdk } = loadSources();

const pools: Record<number, string[]> = {};
const unchecked: string[] = [];
let appended = 0;
let rejected = 0;

for (let len = TARGET_MIN; len <= TARGET_MAX; len++) {
	const frozen = published[len] ?? [];
	const seen = new Set(frozen);
	const candidates = eligible[len].filter((w) => !seen.has(w));

	const fresh: string[] = [];
	for (const word of candidates) {
		const verdict = tdk[word];
		if (verdict === undefined) unchecked.push(word);
		else if (verdict === 1) fresh.push(word);
		else rejected++;
	}

	// eligible[] arrives sorted, so this shuffle is the only source of order.
	shuffleInPlace(
		fresh,
		mulberry32(hashSeed(`${frozen.length ? POOL_APPEND_SEED : POOL_SHUFFLE_SEED}:${len}`))
	);
	pools[len] = [...frozen, ...fresh];
	appended += fresh.length;
}

if (unchecked.length > 0) {
	throw new Error(
		`${unchecked.length} aday TDK'de doğrulanmadı (örn. ${unchecked.slice(0, 5).join(', ')}). ` +
			`Önce çalıştır: node scripts/verify-tdk.ts`
	);
}

// ---- invariant: the published schedule must survive verbatim ----

for (let len = TARGET_MIN; len <= TARGET_MAX; len++) {
	const frozen = published[len] ?? [];
	for (let i = 0; i < frozen.length; i++) {
		if (pools[len][i] !== frozen[i]) {
			throw new Error(
				`havuz ${len}, sıra ${i} değişti: "${frozen[i]}" -> "${pools[len][i]}". ` +
					`Havuzlar yalnızca sona eklenebilir; bu değişiklik oynanmış günleri bozar.`
			);
		}
	}
}

// ---- write ----

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
	OUT_PATH,
	JSON.stringify({ version: DATA_VERSION, sources: SOURCES, validation, pools })
);
writeFileSync(
	join(ROOT, 'static', 'data-version.json'),
	JSON.stringify({ version: DATA_VERSION }) + '\n'
);

console.log(`wrote ${OUT_PATH} (${validation.length} validation words)`);
console.log(`wrote static/data-version.json (version ${DATA_VERSION})`);
console.log(`appended ${appended} new targets; ${rejected} rejected for having no TDK entry`);

if (report) {
	// How many words each round of the day consumes, from the round plan.
	const PER_DAY: Record<number, number> = { 4: 3, 5: 4, 6: 4, 7: 4, 8: 3, 9: 3 };
	console.log(`\nmaster entries:      ${master}`);
	console.log(`non-tdk entries:     ${nonTdk}`);
	console.log(`freq threshold:      ${FREQ_THRESHOLD}`);
	console.log(`validation words:    ${validation.length}\n`);
	for (let len = TARGET_MIN; len <= TARGET_MAX; len++) {
		const was = (published[len] ?? []).length;
		const now = pools[len].length;
		const days = Math.floor(now / PER_DAY[len]) + 1;
		console.log(
			`len=${len}: ${String(was).padStart(4)} -> ${String(now).padStart(4)} ` +
				`(+${String(now - was).padStart(3)})  tekrarsız ${days} gün`
		);
	}
}
